app:
  name: "basketball-service"
  version: "1.0.0"

http:
  port: "8080"

logger:
  log_level: "debug"
  rollbar_env: "basketball-service"

postgres:
  postgres_url: "postgres://postgres:postgres@localhost:5432/postgres"

